ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "isBusy" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "busyEstimateMinutes" INTEGER;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "busyMessage" TEXT;
