ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "iyzicoApiKey" TEXT;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "iyzicoSecretKey" TEXT;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "iyzicoBaseUrl" TEXT;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "iyzicoMode" TEXT NOT NULL DEFAULT 'test';
